### ISSUE TITLE
Crash when trying to query metrics

### ISSUE THREAD

**Issue by floribe2000** [phin1x/cups_exporter#1]
Cups Exporter crashes when we try to query the metrics.
Operating system: Arch Linux (Rolling Release)
Cups version: 2.4.7-2
cups_exporter: latest source available at this time
go version: 1.22.0

We get the following error message:
```
panic: interface conversion: interface {} is int, not int8

goroutine 14 [running]:
github.com/phin1x/cups-exporter/internal.(*Exporter).printerMetrics(0xc00007a120, 0xc00007a540)
        .../cups_exporter/internal/printers.go:22 +0x5e5
github.com/phin1x/cups-exporter/internal.(*Exporter).Collect(0xc00007a120, 0xc00007a540)
        .../cups_exporter/internal/exporter.go:110 +0xbc
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
       .../go/pkg/mod/github.com/prometheus/client_golang@v1.15.0/prometheus/registry.go:455 +0x105
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 10
        .../go/pkg/mod/github.com/prometheus/client_golang@v1.15.0/prometheus/registry.go:547 +0xbab
```
I replaced the paths from my local system with ... in the error log.

**Comment by sgohl** [comment]
same problem. did you ever find a solution or replacement ?

**Comment by floribe2000** [comment]
> same problem. did you ever find a solution or replacement ?

in the end, we just fixed the data type in the source code and recompiled the exporter.

**Comment by MichaelOppenheimer** [comment]
> > same problem. did you ever find a solution or replacement ?
> 
> in the end, we just fixed the data type in the source code and recompiled the exporter.

Hi, could you provide the changes you've done?

**Comment by floribe2000** [comment]
> > > same problem. did you ever find a solution or replacement ?
> > 
> > 
> > in the end, we just fixed the data type in the source code and recompiled the exporter.
> 
> Hi, could you provide the changes you've done?

I put the changes in a public fork and opened a PR for it, #2 
Not sure if there are more errors like this, this was the only one I encountered so far.
